### PR TITLE
Added event APIs

### LINKED ISSUE #281: Create event APIs
### User Story
As an adminstrator
I'd like to have a way to define events
So that I can classify check-ins or questionnaire responses

### Acceptance Criteria
- [ ] API created
- [ ] API approved

### Notes
- Defines the API for managing events

### PR DESCRIPTION
**Pull request by mschechter-bellese**
# Description

- Added event APIs
- Fixed several errors in APIs
- Fixed multple inconsistencies in the schema model

Resolves #281 

## Related PRs

List related PRs against other branches:

| branch          | PR       |
| --------------- | -------- |
| Created e-mail APIs | #280  |

## Todos

- [ ] Tests
- [ ] Documentation

## Deploy Notes

- N/A

## Steps to Test or Reproduce

- Verify new contract in [Swagger Editor](https://editor.swagger.io)

## Impacted Areas in Application

List general components of the application that this PR will affect:

- Contract definition

### CODE REVIEW

**Comment by blakenan-bellese** [comment]
- General
  - For me it is a bit confusing to have v1 and v2 described by the same swagger.json.  Can I suggest that we have separate swagger docs/contracts, one for each major version?  We could use the “unimplemented” tag for items in 2.1+.

- /health
  - Suggest providing an example of unhealthy example value.
- /security/token/{email}
  - Assuming that this would, by default, be very restricted to super-mega-admin role (or similar).  Additionally, it could be completely removed/hidden as this capability is only needed to support the email end point.  Similar comments hold for “/role-grants/{email}”.
- /roles
  - Noticed that the “Description” in the contract for each status code is a slightly different, but identical meaning, string than the “message” in the body of each response.  I’d suggest making these identical to reduce complexity and avoid confusion.  This likely applies generally to many endpoints.
  - Might be nice to show an example with multiple permissions in a role.  Read and write to the same endpoint and/or read to two endpoints.  Or, is this not possible and instead, the user needs to make multiple POST calls to “​/roles​/{roleName}​/addPermission”?
- “/role-grants/” and “/role-grants/{email}”
  - Seems like these end points can be unified.  They both allow the caller to add a role-grant to a user given just their email. If that user has credentials, then the email address goes in the body. If the user is a system user without credentials, then the email address goes in the route.  Is the purpose to allow differentiation in their access via role definition that refers to each of these two routes?  May be a moot point based on comments on “/security/token/{email}”.
- “/email”
  - I’m thinking that the schema for the payload should not require “associationType” and should also support “entityType” as a filter param.  If only template is provided, then an email goes to all contacts of all entities.  Any filter params limit those emails.  
- “/email-template”
  - The sample “template” value does not seem to support specification of the email subject line.  Should this be presumed to be supported in the “template” param OR do we need to replace “template” with “subjectTemplate” and “bodyTemplate”?

**Review by blakenan-bellese — APPROVED** [review]
@mschechter-bellese I added a comment on the PR with my feedback.  Take a look.  I'll defer to your discretion on which changes to make immediately.  If you'd like to chat, let me know.  Thanks so much, this is a well thought out and significant improvement to the API.

**Comment by blakenan-bellese** [comment]
A couple more comments:

1. `PUT/users/{email}` parameter implies that this endpoint is used for updating non-system users, but there is no `PUT /users/` for system users.  Seems that either an endpoint is missing of the parameter is misleading.
2. This contract is missing `/questionnaires`.  We should have this for V2.

**Comment by mschechter-bellese** [comment]
>     * General
>       
>       * For me it is a bit confusing to have v1 and v2 described by the same swagger.json.  Can I suggest that we have separate swagger docs/contracts, one for each major version?  We could use the “unimplemented” tag for items in 2.1+.

This is something we need to discuss further.

> 
>     * /health
>       
>       * Suggest providing an example of unhealthy example value.

Added.

> 
>     * /security/token/{email}
>       
>       * Assuming that this would, by default, be very restricted to super-mega-admin role (or similar).  Additionally, it could be completely removed/hidden as this capability is only needed to support the email end point.  Similar comments hold for “/role-grants/{email}”.

API specifications always must have the full API. If an API is restricted, that's orthogonal to the specification

> 
>     * /roles
>       
>       * Noticed that the “Description” in the contract for each status code is a slightly different, but identical meaning, string than the “message” in the body of each response.  I’d suggest making these identical to reduce complexity and avoid confusion.  This likely applies generally to many endpoints.

The description is supposed to provide additional information about the status, and not simply duplicate the message. Also, there are multiple cases where the message will be dynamically generated based on the request content, and that should be reflected to simplify API integration. We've had repeated feedback on MPSM that the examples should be explicit and context-correct; we need to discuss further to see how we want to handle this.

Also, can you please help me understand how the minor variations in description/message could lead to confusion?

>       * Might be nice to show an example with multiple permissions in a role.  Read and write to the same endpoint and/or read to two endpoints.  Or, is this not possible and instead, the user needs to make multiple POST calls to “​/roles​/{roleName}​/addPermission”?

Roles can be created with multiple permissions; this is documented by having the `resources` content be an array. The `addPermission` and `removePermission` endpoints are intended for "tuning" a role, not bulk modification, and only support one resource at a time. 

Please note that a resource consists of a path and one or more HTTP methods.

> 
>     * “/role-grants/” and “/role-grants/{email}”
>       
>       * Seems like these end points can be unified.  They both allow the caller to add a role-grant to a user given just their email. If that user has credentials, then the email address goes in the body. If the user is a system user without credentials, then the email address goes in the route.  Is the purpose to allow differentiation in their access via role definition that refers to each of these two routes?  May be a moot point based on comments on “/security/token/{email}”.

The reason for the separation is to keep the system users and non-system users separate in the implementation. For `POST /role-grants`, we need to verify that the e-mail addresses correspond to valid users, and the underlying association uses the internal user ID (UUID). For the other endpoint, we don't care about cross-referencing, and just use the e-mail address for the Casbin association (although we probably need a check to ensure someone isn't randomly granting roles via this API to system users).

We're using the user's e-mail address as their username, and that's leading to confusion. I think we need to change the `User` definition to have a `username` field (which can be their e-mail address) in addition to the `email` field, and make that the resource identifier throughout.

> 
>     * “/email”
>       
>       * I’m thinking that the schema for the payload should not require “associationType” and should also support “entityType” as a filter param.  If only template is provided, then an email goes to all contacts of all entities.  Any filter params limit those emails.

Yes, that makes sense.

> 
>     * “/email-template”
>       
>       * The sample “template” value does not seem to support specification of the email subject line.  Should this be presumed to be supported in the “template” param OR do we need to replace “template” with “subjectTemplate” and “bodyTemplate”?

A single template should have both subject and body templates; I can add those.

**Comment by mschechter-bellese** [comment]
> A couple more comments:
> 
>     1. `PUT/users/{email}` parameter implies that this endpoint is used for updating non-system users, but there is no `PUT /users/` for system users.  Seems that either an endpoint is missing of the parameter is misleading.

This is only misleading because we have the following constraints:
- Non-system users only identified by their e-mail address
- System users with their external resource identifiers being an e-mail address

The best fix is most likely to change everything over so that users have a `username` field (which can be an e-mail address) in addition to the e-mail address field.

> 
>     2. This contract is missing `/questionnaires`.  We should have this for V2.

See #282

**Review by blakenan-bellese — APPROVED** [review]
Looks good.

**Pull request merged**
