### PR TITLE
Jbixon/dockerhub

### PR DESCRIPTION
**Pull request by jbixon13**
# Description

Add docker push to .travis.yml to push API image to dockerhub

## Todos

- [ ] Versioning
- [ ] Push to dockerhub only on merge to master
- [ ] Documentation

## Impacted Areas in Application

List general components of the application that this PR will affect:

- Frontend dev env

### CODE REVIEW

**Comment by jbixon13** [comment]
Addresses this frontend issue: https://github.com/CodeForBaltimore/Healthcare-Rollcall/issues/37

**Comment by jbixon13** [comment]
Added conditional docker build & push

**Comment by jbixon13** [comment]
looks like it didn't deploy when it was merged to master, it still used the no deploy condition

**Comment by revjtanton** [comment]
> looks like it didn't deploy when it was merged to master, it still used the no deploy condition

Create a new issue for it.

**Pull request merged**
